services:
  job-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobRoles
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobRoles"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - team4-network

  team4-backend:
    image: backend:latest
    build:
      context: .
      dockerfile: .dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:password@job-db:5432/jobRoles
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
    depends_on:
      job-db:
        condition: service_healthy
    networks:
      - team4-network

networks:
  team4-network:
    driver: bridge

volumes:
  postgres_data: